---
title: "Notes -- SQL server functions"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Chapter 1

#### Data types
exact numerics - integers, decimals (precision) \newline

approximate numeric values \newline

Date and time data types (date: YYYY-mm-DD) \newline

Character and unicode character data types \newline

SQL server has other datatypes, binary, image, cursor, xml, spatial geometry, geograpy types

<!-- add a column in SQL server table -->
<!-- ALTER TABLE voters -->
<!-- ADD last_login ____; -->

<!-- datetime, datetime2 -->

#### Implicit conversion

SQL server converts from one type to another

The developer explicitly converts the data (explicit)

<!-- # GETDATE() -->
<!-- error converting datatype varchar to numeric -->

Implicit conversion between data types. Performance impact of implicit conversion. 

When comparing decimals to integers, the integer value is automatically converted to a decimal (decimal has higher precedence). Otherwise, the data after the decimal point would get lost. 

#### Explicit conversion

Implicit - performed automatically, behind the scenes. 

Explicit - performed with the functions CAST() and CONVERT()

CAST(expression AS data_type [(length)])

nvarchar(20)

CONVERT accepts more parameters; 
CONVERT(data_type [(length)], expression[,style])

CAST() vs CONVERT(): CAST() is from the SQL standard, and CONVERT() is SQL server specific; CONVERT() is slightly better in SQL server.



<!-- SELECT  -->
<!-- 	first_name, -->
<!-- 	last_name, -->
<!-- 	total_votes -->
<!-- FROM voters -->
<!-- -- Transform the total_votes to char of length 10 -->
<!-- WHERE CAST(total_votes AS char) LIKE '5%'; -->


<!-- SELECT  -->
<!-- 	email, -->
<!--     -- Convert birthdate to varchar show it like: "Mon dd,yyyy"  -->
<!--     CONVERT(varchar, birthdate, 107) AS birthdate -->
<!-- FROM voters; -->

<!-- SELECT  -->
<!-- 	first_name, -->
<!--     last_name, -->
<!-- 	-- Convert birthdate to varchar(10) and show it as yy/mm/dd. This format corresponds to value 11 of the "style" parameter. -->
<!-- 	CONVERT(varchar, birthdate, 11) AS birthdate, -->
<!--     gender, -->
<!--     country -->
<!-- FROM voters -->
<!-- WHERE country = 'Belgium'  -->
<!--     -- Select only the female voters -->
<!-- 	AND gender = 'F' -->
<!--     -- Select only people who voted more than 20 times   -->
<!--     AND total_votes > 20; -->



### Chapter 2 - Functions that return system date and time

Common mistakes when working with dates and time, inconsistent date time and formats or patterns, arithmetic operations, issues with time zones. 

Time zones in SQL server: local time zone. UTC time zone (Universal Time Coordinate)

Functions that return the date and time of the operating system

Higher-precision - SYSDATETIME(); SYSUTCDATETIME(); SYSDATETIMEOFFSET()

Lower precision - GETDATE(), GETUTCDATE(), CURRENT_TIMESTAMP

Higher-precision functions example

Retrieving only the date; CONVERT()

CONVERT(time, )

<!-- Select the local system's date, including the timezone information -->

<!-- SELECT  -->
<!-- 	SYSDATETIMEOFFSET() AS Timezone; -->


<!-- SELECT  -->
<!-- 	CONVERT(VARCHAR(24), SYSDATETIME(), 107) AS HighPrecision, -->
<!-- 	CONVERT(VARCHAR(24), GETDATE(), 102) AS LowPrecision; -->
	
#### Functions returning date and time parts

YEAR(date) returns the year from the specified date

MONTH(date) 

DAY(date) 

DATENAME(datepart, date)

DECLARE @date datetime = '2019-03-24'

DATEPART() returns an integer representing the specified part of the given date

DATEFROMPARTS(year, month, day)

<!-- SELECT  -->
<!-- 	first_name, -->
<!-- 	last_name, -->
<!--    	-- Extract the year of the first vote -->
<!-- 	YEAR(first_vote_date)  AS first_vote_year, -->
<!--     -- Extract the month of the first vote -->
<!-- 	MONTH(first_vote_date) AS first_vote_month, -->
<!--     -- Extract the day of the first vote -->
<!-- 	DAY(first_vote_date)   AS first_vote_day -->
<!-- FROM voters -->
<!-- -- The year of the first vote should be greater than 2015 -->
<!-- WHERE YEAR(first_vote_date) > 2015 -->
<!-- -- The day should not be the first day of the month -->
<!--   AND DAY(first_vote_date) <> 1; -->



<!-- SELECT  -->
<!-- 	first_name, -->
<!-- 	last_name, -->
<!-- 	first_vote_date, -->
<!--     -- Select the number of the day within the year -->
<!-- 	DATENAME(dayofyear, first_vote_date) AS first_vote_dayofyear -->
<!-- FROM voters; -->


<!-- SELECT  -->
<!-- 	first_name, -->
<!-- 	last_name, -->
<!--    	-- Extract the month number of the first vote -->
<!-- 	DATEPART(MONTH,first_vote_date) AS first_vote_month1, -->
<!-- 	-- Extract the month name of the first vote -->
<!--     DATENAME(MONTH,first_vote_date) AS first_vote_month2, -->
<!-- 	-- Extract the weekday number of the first vote -->
<!-- 	DATEPART(WEEKDAY,first_vote_date) AS first_vote_weekday1, -->
<!--     -- Extract the weekday name of the first vote -->
<!-- 	DATENAME(WEEKDAY,first_vote_date) AS first_vote_weekday2 -->
<!-- FROM voters; -->

#### Performing arithmetics operations on dates

DATEADD(datepart, number, date), 

DATEDIFF(datepart, startdate, enddate),

Arithmetic operations

DECLARE @date1 datetime = '2019-01-01';

#### Validating if an expression is a date

ISDATE()

date, time, datetime gives 1
datetime2 gives 0
other type gives 0

<!-- SET DATEFORMAT {format} -->

mdy, dmy, ymd, ydm, myd

SET DATEFORMAT dmy;

<!-- SET LANGUAGE {language} -->
English, Italian, Spanish
SET LANGUAGE English; (mdy)

<!-- DECLARE @date1 NVARCHAR(20) = '15/2019/4'; -->

<!-- -- Set the date format and check if the variable is a date -->
<!-- SET DATEFORMAT dym; -->
<!-- SELECT ISDATE(@date1) AS result; -->


<!-- DECLARE @date1 NVARCHAR(20) = '30.03.2019'; -->

<!-- -- Set the correct language -->
<!-- SET LANGUAGE Dutch; -->
<!-- SELECT -->
<!-- 	@date1 AS initial_date, -->
<!--     -- Check that the date is valid -->
<!-- 	ISDATE(@date1) AS is_valid, -->
<!--     -- Select the name of the month -->
<!-- 	DATENAME(month, @date1) AS month_name; -->



<!-- DECLARE @date1 NVARCHAR(20) = '12/18/55'; -->

<!-- -- Set the correct language -->
<!-- SET LANGUAGE English; -->
<!-- SELECT -->
<!-- 	@date1 AS initial_date, -->
<!--     -- Check that the date is valid -->
<!-- 	ISDATE(@date1) AS is_valid, -->
<!--     -- Select the week day name -->
<!-- 	DATENAME(weekday, @date1) AS week_day, -->
<!-- 	-- Extract the year from the date -->
<!-- 	YEAR(@date1) AS year_name; -->



<!-- SELECT -->
<!-- 	first_name, -->
<!--     last_name, -->
<!--     birthdate, -->
<!-- 	first_vote_date, -->
<!-- 	-- Find out on which day of the week each participant voted  -->
<!-- 	DATENAME(weekday, first_vote_date) AS first_vote_weekday, -->
<!-- 	-- Find out the year of the first vote -->
<!-- 	YEAR(first_vote_date) AS first_vote_year, -->
<!-- 	-- Discover the participants' age when they joined the contest -->
<!-- 	DATEDIFF(YEAR, birthdate, first_vote_date) AS age_at_first_vote,	 -->
<!-- 	-- Calculate the current age of each voter -->
<!-- 	DATEDIFF(YEAR, birthdate, GETDATE()) AS current_age -->
<!-- FROM voters; -->



### Chapter 3 - Working with Strings


#### Functions for positions
Position functions

LEN(): returns the number of characters of the provided string (including the space at the end of strings)
CHARINDEX(expression_to_find, expression_to_find, [, start location]): looks for a character expression in a given string, returns its starting position
PATINDEX(), similar to CHARINDEX, 

\begin{itemize}
\item match any string of any length \%
\item match on a single character "_", 
\item [] match on any character in the [] brackets (for example, [abc] would match on a, b, or c characters)
\end{itemize}

#### Functions for string transformation

LOWER(): converts everything to lower
UPPER(): converts everything to upper

LEFT(): example, LEFT(country, 3)
RIGHT(): example, RIGHT(email, 4)

LTRIM(): returns a string after removing the leading blanks
RTRIM(): returns a string after removing the trailing blanks
TRIM(): returns a string after removing the blanks or other specified characters
REPLACE(): returns a string where all occurences of an expression are replaced with another one, SELECT REPLACE('I like apples, apples are good.', 'apple', 'orange') AS result;

SUBSTRING(char expression, start, number of characters), returns part of a string


<!-- SELECT  -->
<!-- 	company, -->
<!-- 	bean_type, -->
<!-- 	broad_bean_origin, -->
<!--     -- 'company' and 'broad_bean_origin' should be in uppercase -->
<!-- 	'The company ' +  UPPER(company) + ' uses beans of type "' + bean_type + '", originating from ' + UPPER(broad_bean_origin) + '.' -->
<!-- FROM ratings -->
<!-- WHERE  -->
<!--     -- The 'broad_bean_origin' should not be unknown -->
<!-- 	LOWER(broad_bean_origin) NOT LIKE '%unknown%' -->
<!--      -- The 'bean_type' should not be unknown -->
<!--     AND LOWER(bean_type) NOT LIKE '%unknown%'; -->

<!-- SELECT  -->
<!-- 	first_name, -->
<!-- 	last_name, -->
<!-- 	country, -->
<!--     -- Select only the first 3 characters from the first name -->
<!-- 	LEFT(first_name, 3) AS part1, -->
<!--     -- Select only the last 3 characters from the last name -->
<!--     RIGHT(last_name, 3) AS part2, -->
<!--     -- Select only the last 2 digits from the birth date -->
<!--     RIGHT(birthdate, 2) AS part3, -->
<!--     -- Create the alias for each voter -->
<!--     LEFT(first_name, 3) + RIGHT(last_name, 3) + '_' + RIGHT(birthdate, 2)  -->
<!-- FROM voters; -->

#### Functions manipulating groups of strings

CONCAT(), 

CONCAT_WS(), concatenate with separator

advantage compared to "+", CONCAT() can accommodate all data types

STRING_AGG() with Group by, with the optional <order_clause>

WITHIN GROUP (ORDER BY first_name ASC) AS 

STRING_SPLIT(string, separator)

<!-- SELECT -->
<!-- 	-- Create a list with all bean origins, delimited by comma -->
<!-- 	STRING_AGG(bean_origin, ',') AS bean_origins -->
<!-- FROM ratings -->
<!-- WHERE company IN ('Bar Au Chocolat', 'Chocolate Con Amor', 'East Van Roasters'); -->



<!-- SELECT  -->
<!-- 	company, --
<!-- DECLARE @phrase NVARCHAR(MAX) = 'In the morning I brush my teeth. In the afternoon I take a nap. In the evening I watch TV.' -->

<!-- SELECT value -->
<!-- FROM STRING_SPLIT(@phrase, ' '); -->>
<!--     -- Create a list with all bean origins ordered alphabetically -->
<!-- 	STRING_AGG(bean_origin, ',') WITHIN GROUP (ORDER BY bean_origin ASC) AS bean_origins -->
<!-- FROM ratings -->
<!-- WHERE company IN ('Bar Au Chocolat', 'Chocolate Con Amor', 'East Van Roasters') -->
<!-- -- Specify the columns used for grouping your data -->
<!-- GROUP BY company; -->

<!-- SELECT -->
<!--     -- Concatenate the first and last name -->
<!-- 	CONCAT('***' , first_name, ' ', UPPER(last_name), '***') AS name, -->
<!--     -- Mask the last two digits of the year -->
<!--     REPLACE(birthdate, SUBSTRING(CAST(birthdate AS varchar), 3, 2), 'XX') AS birthdate, -->
<!-- 	email, -->
<!-- 	country -->
<!-- FROM voters -->
<!--    -- Select only voters with a first name less than 5 characters -->
<!-- WHERE LEN(first_name) < 5 -->
<!--    -- Look for this pattern in the email address: "j%[0-9]@yahoo.com" -->
<!-- 	AND PATINDEX('j_a%@yahoo.com', email) > 0;    -->



### Chapter 4 - Recognize numeric data types

#### Aggregate arithmetic functions
COUNT(); returns of items in a group, [ALL] expression, DISTINCT expression, *

DISTINCT counts the number of unique values
* gives the number of all rows

SUM([ALL]  expression)
SUM(DISTINCT expression)

MAX()
MIN()

AVG()
GROUP BY company;

<!-- SELECT  -->
<!-- 	company, -->
<!-- 	-- Calculate the average cocoa percent -->
<!-- 	AVG(cocoa_percent) AS avg_cocoa, -->
<!-- 	-- Calculate the minimum rating received by each company -->
<!-- 	MIN(rating) AS min_rating, -->
<!-- 	-- Calculate the maximum rating received by each company -->
<!-- 	MAX(rating) AS max_rating -->
<!-- FROM ratings -->
<!-- GROUP BY company -->
<!-- -- Order the values by the maximum rating -->
<!-- ORDER BY MAX(rating) DESC; -->

#### Analytic functions

apply to each row, instead of a group

FIRST_VALUE() OVER (PARTITION BY column ORDER BY column ROW_or_RANGE frame)

LAST_VALUE()

ROWS BETWEEN UNBOUNDED AND UNBOUNDED FOLLOWING 


LAG() AND LEAD(), accesses data from a previous row in the same result set

LAG() first one NULL
LEAD() last one NULL


<!-- SELECT  -->
<!-- 	first_name, -->
<!-- 	last_name, -->
<!-- 	total_votes AS votes, -->
<!--     -- Select the number of votes of the next voter -->
<!-- 	LEAD(total_votes) OVER (ORDER BY total_votes) AS votes_next_voter, -->
<!--     -- Calculate the difference between the number of votes -->
<!-- 	LEAD(total_votes) OVER (ORDER BY total_votes) - total_votes AS votes_diff -->
<!-- FROM voters -->
<!-- WHERE country = 'France' -->
<!-- ORDER BY total_votes; -->

<!-- SELECT  -->
<!-- 	broad_bean_origin AS bean_origin, -->
<!-- 	rating, -->
<!-- 	cocoa_percent, -->
<!--     -- Retrieve the cocoa % of the bar with the previous rating -->
<!-- 	LAG(cocoa_percent)  -->
<!-- 		OVER(PARTITION BY broad_bean_origin ORDER BY rating) AS percent_lower_rating -->
<!-- FROM ratings -->
<!-- WHERE company = 'Fruition' -->
<!-- ORDER BY broad_bean_origin, rating ASC; -->


<!-- SELECT  -->
<!-- 	first_name + ' ' + last_name AS name, -->
<!-- 	country, -->
<!-- 	birthdate, -->
<!-- 	-- Retrieve the birthdate of the oldest voter per country -->
<!-- 	FIRST_VALUE(birthdate)  -->
<!-- 	OVER (PARTITION BY country ORDER BY birthdate ASC) AS oldest_voter, -->
<!-- 	-- Retrieve the birthdate of the youngest voter per country -->
<!-- 	LAST_VALUE(birthdate)  -->
<!-- 		OVER (PARTITION BY country ORDER BY birthdate ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING -->
<!-- 				) AS youngest_voter -->
<!-- FROM voters -->
<!-- WHERE country IN ('Spain', 'USA'); -->

#### Mathematical functions
ABS()

SIGN()

Rounding functions

CEILING()
FLOOR()
ROUND(73.715, 2)

POWER(numeric_expression, power)

SQUARE(numeric_expression)

SQRT(numeric_expression) 


<!-- DECLARE @number1 DECIMAL(18,2) = -5.4; -->
<!-- DECLARE @number2 DECIMAL(18,2) = 7.89; -->
<!-- DECLARE @number3 DECIMAL(18,2) = 13.2; -->
<!-- DECLARE @number4 DECIMAL(18,2) = 0.003; -->

<!-- DECLARE @result DECIMAL(18,2) = @number1 * @number2 - @number3 - @number4; -->
<!-- SELECT  -->
<!-- 	@result AS result, -->
<!--     -- Show the absolute value of the result -->
<!-- 	ABS(@result) AS abs_result; -->

